spring.application.name=kargotakip
server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5432/kargodb
spring.datasource.username=postgres
spring.datasource.password=kzy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=32481709324dj2m980ufcn21cnu832cn12345678123456781234567812345678

